services:
  dev-db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: 123
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  test-db:
    image: postgres:13
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: 123
    volumes:
      - test-db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  dev-db-data:
  test-db-data:
