version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: 123
    networks:
      - freecodecamp

networks:
  freecodecamp:
